import java.util.Vector;

public class Puzzle 
{
	private int target;
	private int points;
	private boolean solved;
	private	static int[] primeArray;
	private int factors[];
	private int possibles[];

	public Puzzle()
	{
		target = ((int)(Math.random()* 9000) + 500) * ((int) (Math.random() * 3) + 2) ;
		setUp(target);
	}
	private void log(String s)
	{
//		System.out.println(s);
	}
	public Puzzle(int target)
	{
		setUp(target);
	}
	private void setUp(int numberIn)
	{
		target = numberIn;
		log("Creating puzzle " + target);
		// get factors array
		Vector f = this.getFactors(target);
		possibles = new int[PrimalFactors.POSSIBLES];
		factors = new int[f.size()];
		// calculate points
		// put factors in possibles
		points = 0;
		int possIndex = 0;
		for (int i = 0; i < f.size(); i++)
		{
			factors[i] = ((Integer) f.elementAt(i)).intValue();
			if (!alreadyInPossibles(factors[i]))
			{
				possibles[possIndex++] = factors[i];
			}
			if (factors[i] == 2 || factors[i] == 5)
			{
				points += 1;
			}	
			else if (factors[i] < 20)
			{
				points += 2;
			}
			else if (factors[i] < 55)
			{
				points += 3;
			}
			else
			{
				points += 4;
			}
		}
		log("Puzzle: point count is " + points);
		int primeIndex = 0;
		// put some of the lower factors in
		while (primeIndex < PrimalFactors.POSSIBLES - 8)
		{	
			int rnd = primeArray[primeIndex++];
			if (!alreadyInPossibles(rnd))
			{
				possibles[possIndex++] = rnd;
			}
		}	
		// fill out possibles with random prime factors
		while (possIndex < PrimalFactors.POSSIBLES)
		{
			int rnd = primeArray[(int)(Math.random()* primeArray.length)];
			if (rnd < (int)(target/5) & !alreadyInPossibles(rnd))
			{
				possibles[possIndex++] = rnd;
//				log("adding " + rnd + " to possibles, index is " + possIndex);
			}
		}
		// sort the possibles
		ToMarUtils.arraySort(possibles);
	}
	private boolean alreadyInPossibles(int numberIn)
	{	
		boolean found = false;
		int pIndex = 0;
		while (!found)
		{	
			if (possibles[pIndex] == 0)
			{
				break;
			}	
			if (possibles[pIndex++] == numberIn)
			{
				found = true;
				break;
			}
		}
		log("alreadyInPossibles for " + numberIn + " - " + found);
		return found;
	}	
	public int[] getFactors() 
	{
		return factors;
	}
	public int[] getPossibles() 
	{
		return possibles;
	}
	public int getPoints() 
	{
		return points;
	}
	public void setPoints(int points) 
	{
		this.points = points;
	}
	public boolean isSolved() 
	{
		return solved;
	}
	public void setSolved(boolean solved) 
	{
		this.solved = solved;
	}
	public int getTarget() 
	{
		return target;
	}
	public void setTarget(int target) 
	{
		this.target = target;
	}
	public static void loadPrimes()
	{
		Vector primes = new Vector();
		primes.addElement(new Integer(2));
		primes.addElement(new Integer(3));
		primes.addElement(new Integer(5));
		primes.addElement(new Integer(7));
		primes.addElement(new Integer(11));
		primes.addElement(new Integer(13));
		primes.addElement(new Integer(17));
		primes.addElement(new Integer(19));
		primes.addElement(new Integer(23));
		primes.addElement(new Integer(29));
		primes.addElement(new Integer(31));
		primes.addElement(new Integer(37));
		primes.addElement(new Integer(41));
		primes.addElement(new Integer(43));
		primes.addElement(new Integer(47));
		primes.addElement(new Integer(53));
		primes.addElement(new Integer(59));
		primes.addElement(new Integer(61));
		primes.addElement(new Integer(67));
		primes.addElement(new Integer(71));
		primes.addElement(new Integer(73));
		primes.addElement(new Integer(79));
		primes.addElement(new Integer(83));
		primes.addElement(new Integer(89));
		primes.addElement(new Integer(97));
		primes.addElement(new Integer(101));
		primes.addElement(new Integer(103));
		primes.addElement(new Integer(107));
		primes.addElement(new Integer(109));
		primes.addElement(new Integer(113));
		primes.addElement(new Integer(127));
		primes.addElement(new Integer(131));
		primes.addElement(new Integer(137));
		primes.addElement(new Integer(139));
		primes.addElement(new Integer(149));
		primes.addElement(new Integer(151));
		primes.addElement(new Integer(157));
		primes.addElement(new Integer(163));
		primes.addElement(new Integer(167));
		primes.addElement(new Integer(173));
		primes.addElement(new Integer(179));
		primes.addElement(new Integer(181));
		primes.addElement(new Integer(191));
		primes.addElement(new Integer(193));
		primes.addElement(new Integer(197));
		primes.addElement(new Integer(199));
		primes.addElement(new Integer(211));
		primes.addElement(new Integer(223));
		primes.addElement(new Integer(227));
		primes.addElement(new Integer(229));
		primes.addElement(new Integer(233));
		primes.addElement(new Integer(239));
		primes.addElement(new Integer(241));
		primes.addElement(new Integer(251));
		primes.addElement(new Integer(257));
		primes.addElement(new Integer(263));
		primes.addElement(new Integer(269));
		primes.addElement(new Integer(271));
		primes.addElement(new Integer(277));
		primes.addElement(new Integer(281));
		primes.addElement(new Integer(283));
		primes.addElement(new Integer(293));
		primes.addElement(new Integer(307));
		primes.addElement(new Integer(311));
		primes.addElement(new Integer(313));
		primes.addElement(new Integer(317));
		primes.addElement(new Integer(331));
		primes.addElement(new Integer(337));
		primes.addElement(new Integer(347));
		primes.addElement(new Integer(349));
		primes.addElement(new Integer(353));
		primes.addElement(new Integer(359));
		primes.addElement(new Integer(367));
		primes.addElement(new Integer(373));
		primes.addElement(new Integer(379));
		primes.addElement(new Integer(383));
		primes.addElement(new Integer(389));
		primes.addElement(new Integer(397));
		primes.addElement(new Integer(401));
		primes.addElement(new Integer(409));
		primes.addElement(new Integer(419));
		primes.addElement(new Integer(421));
		primes.addElement(new Integer(431));
		primes.addElement(new Integer(433));
		primes.addElement(new Integer(439));
		primes.addElement(new Integer(443));
		primes.addElement(new Integer(449));
		primes.addElement(new Integer(457));
		primes.addElement(new Integer(461));
		primes.addElement(new Integer(463));
		primes.addElement(new Integer(467));
		primes.addElement(new Integer(479));
		primes.addElement(new Integer(487));
		primes.addElement(new Integer(491));
		primes.addElement(new Integer(499));
		primes.addElement(new Integer(503));
		primes.addElement(new Integer(509));
		primes.addElement(new Integer(521));
		primes.addElement(new Integer(523));
		primes.addElement(new Integer(541));
		primes.addElement(new Integer(547));
		primes.addElement(new Integer(557));
		primes.addElement(new Integer(563));
		primes.addElement(new Integer(569));
		primes.addElement(new Integer(571));
		primes.addElement(new Integer(577));
		primes.addElement(new Integer(587));
		primes.addElement(new Integer(593));
		primes.addElement(new Integer(599));
		primes.addElement(new Integer(601));
		primes.addElement(new Integer(607));
		primes.addElement(new Integer(613));
		primes.addElement(new Integer(617));
		primes.addElement(new Integer(619));
		primes.addElement(new Integer(631));
		primes.addElement(new Integer(641));
		primes.addElement(new Integer(643));
		primes.addElement(new Integer(647));
		primes.addElement(new Integer(653));
		primes.addElement(new Integer(659));
		primes.addElement(new Integer(661));
		primes.addElement(new Integer(673));
		primes.addElement(new Integer(677));
		primes.addElement(new Integer(683));
		primes.addElement(new Integer(691));
		primes.addElement(new Integer(701));
		primes.addElement(new Integer(709));
		primes.addElement(new Integer(719));
		primes.addElement(new Integer(727));
		primes.addElement(new Integer(733));
		primes.addElement(new Integer(739));
		primes.addElement(new Integer(743));
		primes.addElement(new Integer(751));
		primes.addElement(new Integer(757));
		primes.addElement(new Integer(761));
		primes.addElement(new Integer(769));
		primes.addElement(new Integer(773));
		primes.addElement(new Integer(787));
		primes.addElement(new Integer(797));
		primes.addElement(new Integer(809));
		primes.addElement(new Integer(811));
		primes.addElement(new Integer(821));
		primes.addElement(new Integer(823));
		primes.addElement(new Integer(827));
		primes.addElement(new Integer(829));
		primes.addElement(new Integer(839));
		primes.addElement(new Integer(853));
		primes.addElement(new Integer(857));
		primes.addElement(new Integer(859));
		primes.addElement(new Integer(863));
		primes.addElement(new Integer(877));
		primes.addElement(new Integer(881));
		primes.addElement(new Integer(883));
		primes.addElement(new Integer(887));
		primes.addElement(new Integer(907));
		primes.addElement(new Integer(911));
		primes.addElement(new Integer(919));
		primes.addElement(new Integer(929));
		primes.addElement(new Integer(937));
		primes.addElement(new Integer(941));
		primes.addElement(new Integer(947));
		primes.addElement(new Integer(953));
		primes.addElement(new Integer(967));
		primes.addElement(new Integer(971));
		primes.addElement(new Integer(977));
		primes.addElement(new Integer(983));
		primes.addElement(new Integer(991));
		primes.addElement(new Integer(997));
		primes.addElement(new Integer(1009));
		primes.addElement(new Integer(1013));
		primes.addElement(new Integer(1019));
		primes.addElement(new Integer(1021));
		primes.addElement(new Integer(1031));
		primes.addElement(new Integer(1033));
		primes.addElement(new Integer(1039));
		primes.addElement(new Integer(1049));
		primes.addElement(new Integer(1051));
		primes.addElement(new Integer(1061));
		primes.addElement(new Integer(1063));
		primes.addElement(new Integer(1069));
		primes.addElement(new Integer(1087));
		primes.addElement(new Integer(1091));
		primes.addElement(new Integer(1093));
		primes.addElement(new Integer(1097));
		primes.addElement(new Integer(1103));
		primes.addElement(new Integer(1109));
		primes.addElement(new Integer(1117));
		primes.addElement(new Integer(1123));
		primes.addElement(new Integer(1129));
		primes.addElement(new Integer(1151));
		primes.addElement(new Integer(1153));
		primes.addElement(new Integer(1163));
		primes.addElement(new Integer(1171));
		primes.addElement(new Integer(1181));
		primes.addElement(new Integer(1187));
		primes.addElement(new Integer(1193));
		primes.addElement(new Integer(1201));
		primes.addElement(new Integer(1213));
		primes.addElement(new Integer(1217));
		primes.addElement(new Integer(1223));
		primes.addElement(new Integer(1229));
		primes.addElement(new Integer(1231));
		primes.addElement(new Integer(1237));
		primes.addElement(new Integer(1249));
		primes.addElement(new Integer(1259));
		primes.addElement(new Integer(1277));
		primes.addElement(new Integer(1279));
		primes.addElement(new Integer(1283));
		primes.addElement(new Integer(1289));
		primes.addElement(new Integer(1291));
		primes.addElement(new Integer(1297));
		primes.addElement(new Integer(1301));
		primes.addElement(new Integer(1303));
		primes.addElement(new Integer(1307));
		primes.addElement(new Integer(1319));
		primes.addElement(new Integer(1321));
		primes.addElement(new Integer(1327));
		primes.addElement(new Integer(1361));
		primes.addElement(new Integer(1367));
		primes.addElement(new Integer(1373));
		primes.addElement(new Integer(1381));
		primes.addElement(new Integer(1399));
		primes.addElement(new Integer(1409));
		primes.addElement(new Integer(1423));
		primes.addElement(new Integer(1427));
		primes.addElement(new Integer(1429));
		primes.addElement(new Integer(1433));
		primes.addElement(new Integer(1439));
		primes.addElement(new Integer(1447));
		primes.addElement(new Integer(1451));
		primes.addElement(new Integer(1453));
		primes.addElement(new Integer(1459));
		primes.addElement(new Integer(1471));
		primes.addElement(new Integer(1481));
		primes.addElement(new Integer(1483));
		primes.addElement(new Integer(1487));
		primes.addElement(new Integer(1489));
		primes.addElement(new Integer(1493));
		primes.addElement(new Integer(1499));
		primes.addElement(new Integer(1511));
		primes.addElement(new Integer(1523));
		primes.addElement(new Integer(1531));
		primes.addElement(new Integer(1543));
		primes.addElement(new Integer(1549));
		primes.addElement(new Integer(1553));
		primes.addElement(new Integer(1559));
		primes.addElement(new Integer(1567));
		primes.addElement(new Integer(1571));
		primes.addElement(new Integer(1579));
		primes.addElement(new Integer(1583));
		primes.addElement(new Integer(1597));
		primes.addElement(new Integer(1601));
		primes.addElement(new Integer(1607));
		primes.addElement(new Integer(1609));
		primes.addElement(new Integer(1613));
		primes.addElement(new Integer(1619));
		primes.addElement(new Integer(1621));
		primes.addElement(new Integer(1627));
		primes.addElement(new Integer(1637));
		primes.addElement(new Integer(1657));
		primes.addElement(new Integer(1663));
		primes.addElement(new Integer(1667));
		primes.addElement(new Integer(1669));
		primes.addElement(new Integer(1693));
		primes.addElement(new Integer(1697));
		primes.addElement(new Integer(1699));
		primes.addElement(new Integer(1709));
		primes.addElement(new Integer(1721));
		primes.addElement(new Integer(1723));
		primes.addElement(new Integer(1733));
		primes.addElement(new Integer(1741));
		primes.addElement(new Integer(1747));
		primes.addElement(new Integer(1753));
		primes.addElement(new Integer(1759));
		primes.addElement(new Integer(1777));
		primes.addElement(new Integer(1783));
		primes.addElement(new Integer(1787));
		primes.addElement(new Integer(1789));
		primes.addElement(new Integer(1801));
		primes.addElement(new Integer(1811));
		primes.addElement(new Integer(1823));
		primes.addElement(new Integer(1831));
		primes.addElement(new Integer(1847));
		primes.addElement(new Integer(1861));
		primes.addElement(new Integer(1867));
		primes.addElement(new Integer(1871));
		primes.addElement(new Integer(1873));
		primes.addElement(new Integer(1877));
		primes.addElement(new Integer(1879));
		primes.addElement(new Integer(1889));
		primes.addElement(new Integer(1901));
		primes.addElement(new Integer(1907));
		primes.addElement(new Integer(1913));
		primes.addElement(new Integer(1931));
		primes.addElement(new Integer(1933));
		primes.addElement(new Integer(1949));
		primes.addElement(new Integer(1951));
		primes.addElement(new Integer(1973));
		primes.addElement(new Integer(1979));
		primes.addElement(new Integer(1987));
		primes.addElement(new Integer(1993));
		primes.addElement(new Integer(1997));
		primes.addElement(new Integer(1999));
		primes.addElement(new Integer(2003));
		primes.addElement(new Integer(2011));
		primes.addElement(new Integer(2017));
		primes.addElement(new Integer(2027));
		primes.addElement(new Integer(2029));
		primes.addElement(new Integer(2039));
		primes.addElement(new Integer(2053));
		primes.addElement(new Integer(2063));
		primes.addElement(new Integer(2069));
		primes.addElement(new Integer(2081));
		primes.addElement(new Integer(2083));
		primes.addElement(new Integer(2087));
		primes.addElement(new Integer(2089));
		primes.addElement(new Integer(2099));
		primes.addElement(new Integer(2111));
		primes.addElement(new Integer(2113));
		primes.addElement(new Integer(2129));
		primes.addElement(new Integer(2131));
		primes.addElement(new Integer(2137));
		primes.addElement(new Integer(2141));
		primes.addElement(new Integer(2143));
		primes.addElement(new Integer(2153));
		primes.addElement(new Integer(2161));
		primes.addElement(new Integer(2179));
		primes.addElement(new Integer(2203));
		primes.addElement(new Integer(2207));
		primes.addElement(new Integer(2213));
		primes.addElement(new Integer(2221));
		primes.addElement(new Integer(2237));
		primes.addElement(new Integer(2239));
		primes.addElement(new Integer(2243));
		primes.addElement(new Integer(2251));
		primes.addElement(new Integer(2267));
		primes.addElement(new Integer(2269));
		primes.addElement(new Integer(2273));
		primes.addElement(new Integer(2281));
		primes.addElement(new Integer(2287));
		primes.addElement(new Integer(2293));
		primes.addElement(new Integer(2297));
		primes.addElement(new Integer(2309));
		primes.addElement(new Integer(2311));
		primes.addElement(new Integer(2333));
		primes.addElement(new Integer(2339));
		primes.addElement(new Integer(2341));
		primes.addElement(new Integer(2347));
		primes.addElement(new Integer(2351));
		primes.addElement(new Integer(2357));
		primes.addElement(new Integer(2371));
		primes.addElement(new Integer(2377));
		primes.addElement(new Integer(2381));
		primes.addElement(new Integer(2383));
		primes.addElement(new Integer(2389));
		primes.addElement(new Integer(2393));
		primes.addElement(new Integer(2399));
		primes.addElement(new Integer(2411));
		primes.addElement(new Integer(2417));
		primes.addElement(new Integer(2423));
		primes.addElement(new Integer(2437));
		primes.addElement(new Integer(2441));
		primes.addElement(new Integer(2447));
		primes.addElement(new Integer(2459));
		primes.addElement(new Integer(2467));
		primes.addElement(new Integer(2473));
		primes.addElement(new Integer(2477));
		primes.addElement(new Integer(2503));
		primes.addElement(new Integer(2521));
		primes.addElement(new Integer(2531));
		primes.addElement(new Integer(2539));
		primes.addElement(new Integer(2543));
		primes.addElement(new Integer(2549));
		primes.addElement(new Integer(2551));
		primes.addElement(new Integer(2557));
		primes.addElement(new Integer(2579));
		primes.addElement(new Integer(2591));
		primes.addElement(new Integer(2593));
		primes.addElement(new Integer(2609));
		primes.addElement(new Integer(2617));
		primes.addElement(new Integer(2621));
		primes.addElement(new Integer(2633));
		primes.addElement(new Integer(2647));
		primes.addElement(new Integer(2657));
		primes.addElement(new Integer(2659));
		primes.addElement(new Integer(2663));
		primes.addElement(new Integer(2671));
		primes.addElement(new Integer(2677));
		primes.addElement(new Integer(2683));
		primes.addElement(new Integer(2687));
		primes.addElement(new Integer(2689));
		primes.addElement(new Integer(2693));
		primes.addElement(new Integer(2699));
		primes.addElement(new Integer(2707));
		primes.addElement(new Integer(2711));
		primes.addElement(new Integer(2713));
		primes.addElement(new Integer(2719));
		primes.addElement(new Integer(2729));
		primes.addElement(new Integer(2731));
		primes.addElement(new Integer(2741));
		primes.addElement(new Integer(2749));
		primes.addElement(new Integer(2753));
		primes.addElement(new Integer(2767));
		primes.addElement(new Integer(2777));
		primes.addElement(new Integer(2789));
		primes.addElement(new Integer(2791));
		primes.addElement(new Integer(2797));
		primes.addElement(new Integer(2801));
		primes.addElement(new Integer(2803));
		primes.addElement(new Integer(2819));
		primes.addElement(new Integer(2833));
		primes.addElement(new Integer(2837));
		primes.addElement(new Integer(2843));
		primes.addElement(new Integer(2851));
		primes.addElement(new Integer(2857));
		primes.addElement(new Integer(2861));
		primes.addElement(new Integer(2879));
		primes.addElement(new Integer(2887));
		primes.addElement(new Integer(2897));
		primes.addElement(new Integer(2903));
		primes.addElement(new Integer(2909));
		primes.addElement(new Integer(2917));
		primes.addElement(new Integer(2927));
		primes.addElement(new Integer(2939));
		primes.addElement(new Integer(2953));
		primes.addElement(new Integer(2957));
		primes.addElement(new Integer(2963));
		primes.addElement(new Integer(2969));
		primes.addElement(new Integer(2971));
		primes.addElement(new Integer(2999));
		primes.addElement(new Integer(3001));
		primes.addElement(new Integer(3011));
		primes.addElement(new Integer(3019));
		primes.addElement(new Integer(3023));
		primes.addElement(new Integer(3037));
		primes.addElement(new Integer(3041));
		primes.addElement(new Integer(3049));
		primes.addElement(new Integer(3061));
		primes.addElement(new Integer(3067));
		primes.addElement(new Integer(3079));
		primes.addElement(new Integer(3083));
		primes.addElement(new Integer(3089));
		primes.addElement(new Integer(3109));
		primes.addElement(new Integer(3119));
		primes.addElement(new Integer(3121));
		primes.addElement(new Integer(3137));
		primes.addElement(new Integer(3163));
		primes.addElement(new Integer(3167));
		primes.addElement(new Integer(3169));
		primes.addElement(new Integer(3181));
		primes.addElement(new Integer(3187));
		primes.addElement(new Integer(3191));
		primes.addElement(new Integer(3203));
		primes.addElement(new Integer(3209));
		primes.addElement(new Integer(3217));
		primes.addElement(new Integer(3221));
		primes.addElement(new Integer(3229));
		primes.addElement(new Integer(3251));
		primes.addElement(new Integer(3253));
		primes.addElement(new Integer(3257));
		primes.addElement(new Integer(3259));
		primes.addElement(new Integer(3271));
		primes.addElement(new Integer(3299));
		primes.addElement(new Integer(3301));
		primes.addElement(new Integer(3307));
		primes.addElement(new Integer(3313));
		primes.addElement(new Integer(3319));
		primes.addElement(new Integer(3323));
		primes.addElement(new Integer(3329));
		primes.addElement(new Integer(3331));
		primes.addElement(new Integer(3343));
		primes.addElement(new Integer(3347));
		primes.addElement(new Integer(3359));
		primes.addElement(new Integer(3361));
		primes.addElement(new Integer(3371));
		primes.addElement(new Integer(3373));
		primes.addElement(new Integer(3389));
		primes.addElement(new Integer(3391));
		primes.addElement(new Integer(3407));
		primes.addElement(new Integer(3413));
		primes.addElement(new Integer(3433));
		primes.addElement(new Integer(3449));
		primes.addElement(new Integer(3457));
		primes.addElement(new Integer(3461));
		primes.addElement(new Integer(3463));
		primes.addElement(new Integer(3467));
		primes.addElement(new Integer(3469));
		primes.addElement(new Integer(3491));
		primes.addElement(new Integer(3499));
		primes.addElement(new Integer(3511));
		primes.addElement(new Integer(3517));
		primes.addElement(new Integer(3527));
		primes.addElement(new Integer(3529));
		primes.addElement(new Integer(3533));
		primes.addElement(new Integer(3539));
		primes.addElement(new Integer(3541));
		primes.addElement(new Integer(3547));
		primes.addElement(new Integer(3557));
		primes.addElement(new Integer(3559));
		primes.addElement(new Integer(3571));
		primes.addElement(new Integer(3581));
		primes.addElement(new Integer(3583));
		primes.addElement(new Integer(3593));
		primes.addElement(new Integer(3607));
		primes.addElement(new Integer(3613));
		primes.addElement(new Integer(3617));
		primes.addElement(new Integer(3623));
		primes.addElement(new Integer(3631));
		primes.addElement(new Integer(3637));
		primes.addElement(new Integer(3643));
		primes.addElement(new Integer(3659));
		primes.addElement(new Integer(3671));
		primes.addElement(new Integer(3673));
		primes.addElement(new Integer(3677));
		primes.addElement(new Integer(3691));
		primes.addElement(new Integer(3697));
		primes.addElement(new Integer(3701));
		primes.addElement(new Integer(3709));
		primes.addElement(new Integer(3719));
		primes.addElement(new Integer(3727));
		primes.addElement(new Integer(3733));
		primes.addElement(new Integer(3739));
		primes.addElement(new Integer(3761));
		primes.addElement(new Integer(3767));
		primes.addElement(new Integer(3769));
		primes.addElement(new Integer(3779));
		primes.addElement(new Integer(3793));
		primes.addElement(new Integer(3797));
		primes.addElement(new Integer(3803));
		primes.addElement(new Integer(3821));
		primes.addElement(new Integer(3823));
		primes.addElement(new Integer(3833));
		primes.addElement(new Integer(3847));
		primes.addElement(new Integer(3851));
		primes.addElement(new Integer(3853));
		primes.addElement(new Integer(3863));
		primes.addElement(new Integer(3877));
		primes.addElement(new Integer(3881));
		primes.addElement(new Integer(3889));
		primes.addElement(new Integer(3907));
		primes.addElement(new Integer(3911));
		primes.addElement(new Integer(3917));
		primes.addElement(new Integer(3919));
		primes.addElement(new Integer(3923));
		primes.addElement(new Integer(3929));
		primes.addElement(new Integer(3931));
		primes.addElement(new Integer(3943));
		primes.addElement(new Integer(3947));
		primes.addElement(new Integer(3967));
		primes.addElement(new Integer(3989));
		primes.addElement(new Integer(4001));
		primes.addElement(new Integer(4003));
		primes.addElement(new Integer(4007));
		primes.addElement(new Integer(4013));
		primes.addElement(new Integer(4019));
		primes.addElement(new Integer(4021));
		primes.addElement(new Integer(4027));
		primes.addElement(new Integer(4049));
		primes.addElement(new Integer(4051));
		primes.addElement(new Integer(4057));
		primes.addElement(new Integer(4073));
		primes.addElement(new Integer(4079));
		primes.addElement(new Integer(4091));
		primes.addElement(new Integer(4093));
		primes.addElement(new Integer(4099));
		primes.addElement(new Integer(4111));
		primes.addElement(new Integer(4127));
		primes.addElement(new Integer(4129));
		primes.addElement(new Integer(4133));
		primes.addElement(new Integer(4139));
		primes.addElement(new Integer(4153));
		primes.addElement(new Integer(4157));
		primes.addElement(new Integer(4159));
		primes.addElement(new Integer(4177));
		primes.addElement(new Integer(4201));
		primes.addElement(new Integer(4211));
		primes.addElement(new Integer(4217));
		primes.addElement(new Integer(4219));
		primes.addElement(new Integer(4229));
		primes.addElement(new Integer(4231));
		primes.addElement(new Integer(4241));
		primes.addElement(new Integer(4243));
		primes.addElement(new Integer(4253));
		primes.addElement(new Integer(4259));
		primes.addElement(new Integer(4261));
		primes.addElement(new Integer(4271));
		primes.addElement(new Integer(4273));
		primes.addElement(new Integer(4283));
		primes.addElement(new Integer(4289));
		primes.addElement(new Integer(4297));
		primes.addElement(new Integer(4327));
		primes.addElement(new Integer(4337));
		primes.addElement(new Integer(4339));
		primes.addElement(new Integer(4349));
		primes.addElement(new Integer(4357));
		primes.addElement(new Integer(4363));
		primes.addElement(new Integer(4373));
		primes.addElement(new Integer(4391));
		primes.addElement(new Integer(4397));
		primes.addElement(new Integer(4409));
		primes.addElement(new Integer(4421));
		primes.addElement(new Integer(4423));
		primes.addElement(new Integer(4441));
		primes.addElement(new Integer(4447));
		primes.addElement(new Integer(4451));
		primes.addElement(new Integer(4457));
		primes.addElement(new Integer(4463));
		primes.addElement(new Integer(4481));
		primes.addElement(new Integer(4483));
		primes.addElement(new Integer(4493));
		primes.addElement(new Integer(4507));
		primes.addElement(new Integer(4513));
		primes.addElement(new Integer(4517));
		primes.addElement(new Integer(4519));
		primes.addElement(new Integer(4523));
		primes.addElement(new Integer(4547));
		primes.addElement(new Integer(4549));
		primes.addElement(new Integer(4561));
		primes.addElement(new Integer(4567));
		primes.addElement(new Integer(4583));
		primes.addElement(new Integer(4591));
		primes.addElement(new Integer(4597));
		primes.addElement(new Integer(4603));
		primes.addElement(new Integer(4621));
		primes.addElement(new Integer(4637));
		primes.addElement(new Integer(4639));
		primes.addElement(new Integer(4643));
		primes.addElement(new Integer(4649));
		primes.addElement(new Integer(4651));
		primes.addElement(new Integer(4657));
		primes.addElement(new Integer(4663));
		primes.addElement(new Integer(4673));
		primes.addElement(new Integer(4679));
		primes.addElement(new Integer(4691));
		primes.addElement(new Integer(4703));
		primes.addElement(new Integer(4721));
		primes.addElement(new Integer(4723));
		primes.addElement(new Integer(4729));
		primes.addElement(new Integer(4733));
		primes.addElement(new Integer(4751));
		primes.addElement(new Integer(4759));
		primes.addElement(new Integer(4783));
		primes.addElement(new Integer(4787));
		primes.addElement(new Integer(4789));
		primes.addElement(new Integer(4793));
		primes.addElement(new Integer(4799));
		primes.addElement(new Integer(4801));
		primes.addElement(new Integer(4813));
		primes.addElement(new Integer(4817));
		primes.addElement(new Integer(4831));
		primes.addElement(new Integer(4861));
		primes.addElement(new Integer(4871));
		primes.addElement(new Integer(4877));
		primes.addElement(new Integer(4889));
		primes.addElement(new Integer(4903));
		primes.addElement(new Integer(4909));
		primes.addElement(new Integer(4919));
		primes.addElement(new Integer(4931));
		primes.addElement(new Integer(4933));
		primes.addElement(new Integer(4937));
		primes.addElement(new Integer(4943));
		primes.addElement(new Integer(4951));
		primes.addElement(new Integer(4957));
		primes.addElement(new Integer(4967));
		primes.addElement(new Integer(4969));
		primes.addElement(new Integer(4973));
		primes.addElement(new Integer(4987));
		primes.addElement(new Integer(4993));
		primes.addElement(new Integer(4999));
		primes.addElement(new Integer(5003));
		primes.addElement(new Integer(5009));
		primes.addElement(new Integer(5011));
		primes.addElement(new Integer(5021));
		primes.addElement(new Integer(5023));
		primes.addElement(new Integer(5039));
		primes.addElement(new Integer(5051));
		primes.addElement(new Integer(5059));
		primes.addElement(new Integer(5077));
		primes.addElement(new Integer(5081));
		primes.addElement(new Integer(5087));
		primes.addElement(new Integer(5099));
		primes.addElement(new Integer(5101));
		primes.addElement(new Integer(5107));
		primes.addElement(new Integer(5113));
		primes.addElement(new Integer(5119));
		primes.addElement(new Integer(5147));
		primes.addElement(new Integer(5153));
		primes.addElement(new Integer(5167));
		primes.addElement(new Integer(5171));
		primes.addElement(new Integer(5179));
		primes.addElement(new Integer(5189));
		primes.addElement(new Integer(5197));
		primes.addElement(new Integer(5209));
		primes.addElement(new Integer(5227));
		primes.addElement(new Integer(5231));
		primes.addElement(new Integer(5233));
		primes.addElement(new Integer(5237));
		primes.addElement(new Integer(5261));
		primes.addElement(new Integer(5273));
		primes.addElement(new Integer(5279));
		primes.addElement(new Integer(5281));
		primes.addElement(new Integer(5297));
		primes.addElement(new Integer(5303));
		primes.addElement(new Integer(5309));
		primes.addElement(new Integer(5323));
		primes.addElement(new Integer(5333));
		primes.addElement(new Integer(5347));
		primes.addElement(new Integer(5351));
		primes.addElement(new Integer(5381));
		primes.addElement(new Integer(5387));
		primes.addElement(new Integer(5393));
		primes.addElement(new Integer(5399));
		primes.addElement(new Integer(5407));
		primes.addElement(new Integer(5413));
		primes.addElement(new Integer(5417));
		primes.addElement(new Integer(5419));
		primes.addElement(new Integer(5431));
		primes.addElement(new Integer(5437));
		primes.addElement(new Integer(5441));
		primes.addElement(new Integer(5443));
		primes.addElement(new Integer(5449));
		primes.addElement(new Integer(5471));
		primes.addElement(new Integer(5477));
		primes.addElement(new Integer(5479));
		primes.addElement(new Integer(5483));
		primes.addElement(new Integer(5501));
		primes.addElement(new Integer(5503));
		primes.addElement(new Integer(5507));
		primes.addElement(new Integer(5519));
		primes.addElement(new Integer(5521));
		primes.addElement(new Integer(5527));
		primes.addElement(new Integer(5531));
		primes.addElement(new Integer(5557));
		primes.addElement(new Integer(5563));
		primes.addElement(new Integer(5569));
		primes.addElement(new Integer(5573));
		primes.addElement(new Integer(5581));
		primes.addElement(new Integer(5591));
		primes.addElement(new Integer(5623));
		primes.addElement(new Integer(5639));
		primes.addElement(new Integer(5641));
		primes.addElement(new Integer(5647));
		primes.addElement(new Integer(5651));
		primes.addElement(new Integer(5653));
		primes.addElement(new Integer(5657));
		primes.addElement(new Integer(5659));
		primes.addElement(new Integer(5669));
		primes.addElement(new Integer(5683));
		primes.addElement(new Integer(5689));
		primes.addElement(new Integer(5693));
		primes.addElement(new Integer(5701));
		primes.addElement(new Integer(5711));
		primes.addElement(new Integer(5717));
		primes.addElement(new Integer(5737));
		primes.addElement(new Integer(5741));
		primes.addElement(new Integer(5743));
		primes.addElement(new Integer(5749));
		primes.addElement(new Integer(5779));
		primes.addElement(new Integer(5783));
		primes.addElement(new Integer(5791));
		primes.addElement(new Integer(5801));
		primes.addElement(new Integer(5807));
		primes.addElement(new Integer(5813));
		primes.addElement(new Integer(5821));
		primes.addElement(new Integer(5827));
		primes.addElement(new Integer(5839));
		primes.addElement(new Integer(5843));
		primes.addElement(new Integer(5849));
		primes.addElement(new Integer(5851));
		primes.addElement(new Integer(5857));
		primes.addElement(new Integer(5861));
		primes.addElement(new Integer(5867));
		primes.addElement(new Integer(5869));
		primes.addElement(new Integer(5879));
		primes.addElement(new Integer(5881));
		primes.addElement(new Integer(5897));
		primes.addElement(new Integer(5903));
		primes.addElement(new Integer(5923));
		primes.addElement(new Integer(5927));
		primes.addElement(new Integer(5939));
		primes.addElement(new Integer(5953));
		primes.addElement(new Integer(5981));
		primes.addElement(new Integer(5987));
		primes.addElement(new Integer(6007));
		primes.addElement(new Integer(6011));
		primes.addElement(new Integer(6029));
		primes.addElement(new Integer(6037));
		primes.addElement(new Integer(6043));
		primes.addElement(new Integer(6047));
		primes.addElement(new Integer(6053));
		primes.addElement(new Integer(6067));
		primes.addElement(new Integer(6073));
		primes.addElement(new Integer(6079));
		primes.addElement(new Integer(6089));
		primes.addElement(new Integer(6091));
		primes.addElement(new Integer(6101));
		primes.addElement(new Integer(6113));
		primes.addElement(new Integer(6121));
		primes.addElement(new Integer(6131));
		primes.addElement(new Integer(6133));
		primes.addElement(new Integer(6143));
		primes.addElement(new Integer(6151));
		primes.addElement(new Integer(6163));
		primes.addElement(new Integer(6173));
		primes.addElement(new Integer(6197));
		primes.addElement(new Integer(6199));
		primes.addElement(new Integer(6203));
		primes.addElement(new Integer(6211));
		primes.addElement(new Integer(6217));
		primes.addElement(new Integer(6221));
		primes.addElement(new Integer(6229));
		primes.addElement(new Integer(6247));
		primes.addElement(new Integer(6257));
		primes.addElement(new Integer(6263));
		primes.addElement(new Integer(6269));
		primes.addElement(new Integer(6271));
		primes.addElement(new Integer(6277));
		primes.addElement(new Integer(6287));
		primes.addElement(new Integer(6299));
		primes.addElement(new Integer(6301));
		primes.addElement(new Integer(6311));
		primes.addElement(new Integer(6317));
		primes.addElement(new Integer(6323));
		primes.addElement(new Integer(6329));
		primes.addElement(new Integer(6337));
		primes.addElement(new Integer(6343));
		primes.addElement(new Integer(6353));
		primes.addElement(new Integer(6359));
		primes.addElement(new Integer(6361));
		primes.addElement(new Integer(6367));
		primes.addElement(new Integer(6373));
		primes.addElement(new Integer(6379));
		primes.addElement(new Integer(6389));
		primes.addElement(new Integer(6397));
		primes.addElement(new Integer(6421));
		primes.addElement(new Integer(6427));
		primes.addElement(new Integer(6449));
		primes.addElement(new Integer(6451));
		primes.addElement(new Integer(6469));
		primes.addElement(new Integer(6473));
		primes.addElement(new Integer(6481));
		primes.addElement(new Integer(6491));
		primes.addElement(new Integer(6521));
		primes.addElement(new Integer(6529));
		primes.addElement(new Integer(6547));
		primes.addElement(new Integer(6551));
		primes.addElement(new Integer(6553));
		primes.addElement(new Integer(6563));
		primes.addElement(new Integer(6569));
		primes.addElement(new Integer(6571));
		primes.addElement(new Integer(6577));
		primes.addElement(new Integer(6581));
		primes.addElement(new Integer(6599));
		primes.addElement(new Integer(6607));
		primes.addElement(new Integer(6619));
		primes.addElement(new Integer(6637));
		primes.addElement(new Integer(6653));
		primes.addElement(new Integer(6659));
		primes.addElement(new Integer(6661));
		primes.addElement(new Integer(6673));
		primes.addElement(new Integer(6679));
		primes.addElement(new Integer(6689));
		primes.addElement(new Integer(6691));
		primes.addElement(new Integer(6701));
		primes.addElement(new Integer(6703));
		primes.addElement(new Integer(6709));
		primes.addElement(new Integer(6719));
		primes.addElement(new Integer(6733));
		primes.addElement(new Integer(6737));
		primes.addElement(new Integer(6761));
		primes.addElement(new Integer(6763));
		primes.addElement(new Integer(6779));
		primes.addElement(new Integer(6781));
		primes.addElement(new Integer(6791));
		primes.addElement(new Integer(6793));
		primes.addElement(new Integer(6803));
		primes.addElement(new Integer(6823));
		primes.addElement(new Integer(6827));
		primes.addElement(new Integer(6829));
		primes.addElement(new Integer(6833));
		primes.addElement(new Integer(6841));
		primes.addElement(new Integer(6857));
		primes.addElement(new Integer(6863));
		primes.addElement(new Integer(6869));
		primes.addElement(new Integer(6871));
		primes.addElement(new Integer(6883));
		primes.addElement(new Integer(6899));
		primes.addElement(new Integer(6907));
		primes.addElement(new Integer(6911));
		primes.addElement(new Integer(6917));
		primes.addElement(new Integer(6947));
		primes.addElement(new Integer(6949));
		primes.addElement(new Integer(6959));
		primes.addElement(new Integer(6961));
		primes.addElement(new Integer(6967));
		primes.addElement(new Integer(6971));
		primes.addElement(new Integer(6977));
		primes.addElement(new Integer(6983));
		primes.addElement(new Integer(6991));
		primes.addElement(new Integer(6997));
		primes.addElement(new Integer(7001));
		primes.addElement(new Integer(7013));
		primes.addElement(new Integer(7019));
		primes.addElement(new Integer(7027));
		primes.addElement(new Integer(7039));
		primes.addElement(new Integer(7043));
		primes.addElement(new Integer(7057));
		primes.addElement(new Integer(7069));
		primes.addElement(new Integer(7079));
		primes.addElement(new Integer(7103));
		primes.addElement(new Integer(7109));
		primes.addElement(new Integer(7121));
		primes.addElement(new Integer(7127));
		primes.addElement(new Integer(7129));
		primes.addElement(new Integer(7151));
		primes.addElement(new Integer(7159));
		primes.addElement(new Integer(7177));
		primes.addElement(new Integer(7187));
		primes.addElement(new Integer(7193));
		primes.addElement(new Integer(7207));
		primes.addElement(new Integer(7211));
		primes.addElement(new Integer(7213));
		primes.addElement(new Integer(7219));
		primes.addElement(new Integer(7229));
		primes.addElement(new Integer(7237));
		primes.addElement(new Integer(7243));
		primes.addElement(new Integer(7247));
		primes.addElement(new Integer(7253));
		primes.addElement(new Integer(7283));
		primes.addElement(new Integer(7297));
		primes.addElement(new Integer(7307));
		primes.addElement(new Integer(7309));
		primes.addElement(new Integer(7321));
		primes.addElement(new Integer(7331));
		primes.addElement(new Integer(7333));
		primes.addElement(new Integer(7349));
		primes.addElement(new Integer(7351));
		primes.addElement(new Integer(7369));
		primes.addElement(new Integer(7393));
		primes.addElement(new Integer(7411));
		primes.addElement(new Integer(7417));
		primes.addElement(new Integer(7433));
		primes.addElement(new Integer(7451));
		primes.addElement(new Integer(7457));
		primes.addElement(new Integer(7459));
		primes.addElement(new Integer(7477));
		primes.addElement(new Integer(7481));
		primes.addElement(new Integer(7487));
		primes.addElement(new Integer(7489));
		primes.addElement(new Integer(7499));
		primes.addElement(new Integer(7507));
		primes.addElement(new Integer(7517));
		primes.addElement(new Integer(7523));
		primes.addElement(new Integer(7529));
		primes.addElement(new Integer(7537));
		primes.addElement(new Integer(7541));
		primes.addElement(new Integer(7547));
		primes.addElement(new Integer(7549));
		primes.addElement(new Integer(7559));
		primes.addElement(new Integer(7561));
		primes.addElement(new Integer(7573));
		primes.addElement(new Integer(7577));
		primes.addElement(new Integer(7583));
		primes.addElement(new Integer(7589));
		primes.addElement(new Integer(7591));
		primes.addElement(new Integer(7603));
		primes.addElement(new Integer(7607));
		primes.addElement(new Integer(7621));
		primes.addElement(new Integer(7639));
		primes.addElement(new Integer(7643));
		primes.addElement(new Integer(7649));
		primes.addElement(new Integer(7669));
		primes.addElement(new Integer(7673));
		primes.addElement(new Integer(7681));
		primes.addElement(new Integer(7687));
		primes.addElement(new Integer(7691));
		primes.addElement(new Integer(7699));
		primes.addElement(new Integer(7703));
		primes.addElement(new Integer(7717));
		primes.addElement(new Integer(7723));
		primes.addElement(new Integer(7727));
		primes.addElement(new Integer(7741));
		primes.addElement(new Integer(7753));
		primes.addElement(new Integer(7757));
		primes.addElement(new Integer(7759));
		primes.addElement(new Integer(7789));
		primes.addElement(new Integer(7793));
		primes.addElement(new Integer(7817));
		primes.addElement(new Integer(7823));
		primes.addElement(new Integer(7829));
		primes.addElement(new Integer(7841));
		primes.addElement(new Integer(7853));
		primes.addElement(new Integer(7867));
		primes.addElement(new Integer(7873));
		primes.addElement(new Integer(7877));
		primes.addElement(new Integer(7879));
		primes.addElement(new Integer(7883));
		primes.addElement(new Integer(7901));
		primes.addElement(new Integer(7907));
		primes.addElement(new Integer(7919));
		primes.addElement(new Integer(7927));
		primes.addElement(new Integer(7933));
		primes.addElement(new Integer(7937));
		primes.addElement(new Integer(7949));
		primes.addElement(new Integer(7951));
		primes.addElement(new Integer(7963));
		primes.addElement(new Integer(7993));
		primes.addElement(new Integer(8009));
		primes.addElement(new Integer(8011));
		primes.addElement(new Integer(8017));
		primes.addElement(new Integer(8039));
		primes.addElement(new Integer(8053));
		primes.addElement(new Integer(8059));
		primes.addElement(new Integer(8069));
		primes.addElement(new Integer(8081));
		primes.addElement(new Integer(8087));
		primes.addElement(new Integer(8089));
		primes.addElement(new Integer(8093));
		primes.addElement(new Integer(8101));
		primes.addElement(new Integer(8111));
		primes.addElement(new Integer(8117));
		primes.addElement(new Integer(8123));
		primes.addElement(new Integer(8147));
		primes.addElement(new Integer(8161));
		primes.addElement(new Integer(8167));
		primes.addElement(new Integer(8171));
		primes.addElement(new Integer(8179));
		primes.addElement(new Integer(8191));
		primes.addElement(new Integer(8209));
		primes.addElement(new Integer(8219));
		primes.addElement(new Integer(8221));
		primes.addElement(new Integer(8231));
		primes.addElement(new Integer(8233));
		primes.addElement(new Integer(8237));
		primes.addElement(new Integer(8243));
		primes.addElement(new Integer(8263));
		primes.addElement(new Integer(8269));
		primes.addElement(new Integer(8273));
		primes.addElement(new Integer(8287));
		primes.addElement(new Integer(8291));
		primes.addElement(new Integer(8293));
		primes.addElement(new Integer(8297));
		primes.addElement(new Integer(8311));
		primes.addElement(new Integer(8317));
		primes.addElement(new Integer(8329));
		primes.addElement(new Integer(8353));
		primes.addElement(new Integer(8363));
		primes.addElement(new Integer(8369));
		primes.addElement(new Integer(8377));
		primes.addElement(new Integer(8387));
		primes.addElement(new Integer(8389));
		primes.addElement(new Integer(8419));
		primes.addElement(new Integer(8423));
		primes.addElement(new Integer(8429));
		primes.addElement(new Integer(8431));
		primes.addElement(new Integer(8443));
		primes.addElement(new Integer(8447));
		primes.addElement(new Integer(8461));
		primes.addElement(new Integer(8467));
		primes.addElement(new Integer(8501));
		primes.addElement(new Integer(8513));
		primes.addElement(new Integer(8521));
		primes.addElement(new Integer(8527));
		primes.addElement(new Integer(8537));
		primes.addElement(new Integer(8539));
		primes.addElement(new Integer(8543));
		primes.addElement(new Integer(8563));
		primes.addElement(new Integer(8573));
		primes.addElement(new Integer(8581));
		primes.addElement(new Integer(8597));
		primes.addElement(new Integer(8599));
		primes.addElement(new Integer(8609));
		primes.addElement(new Integer(8623));
		primes.addElement(new Integer(8627));
		primes.addElement(new Integer(8629));
		primes.addElement(new Integer(8641));
		primes.addElement(new Integer(8647));
		primes.addElement(new Integer(8663));
		primes.addElement(new Integer(8669));
		primes.addElement(new Integer(8677));
		primes.addElement(new Integer(8681));
		primes.addElement(new Integer(8689));
		primes.addElement(new Integer(8693));
		primes.addElement(new Integer(8699));
		primes.addElement(new Integer(8707));
		primes.addElement(new Integer(8713));
		primes.addElement(new Integer(8719));
		primes.addElement(new Integer(8731));
		primes.addElement(new Integer(8737));
		primes.addElement(new Integer(8741));
		primes.addElement(new Integer(8747));
		primes.addElement(new Integer(8753));
		primes.addElement(new Integer(8761));
		primes.addElement(new Integer(8779));
		primes.addElement(new Integer(8783));
		primes.addElement(new Integer(8803));
		primes.addElement(new Integer(8807));
		primes.addElement(new Integer(8819));
		primes.addElement(new Integer(8821));
		primes.addElement(new Integer(8831));
		primes.addElement(new Integer(8837));
		primes.addElement(new Integer(8839));
		primes.addElement(new Integer(8849));
		primes.addElement(new Integer(8861));
		primes.addElement(new Integer(8863));
		primes.addElement(new Integer(8867));
		primes.addElement(new Integer(8887));
		primes.addElement(new Integer(8893));
		primes.addElement(new Integer(8923));
		primes.addElement(new Integer(8929));
		primes.addElement(new Integer(8933));
		primes.addElement(new Integer(8941));
		primes.addElement(new Integer(8951));
		primes.addElement(new Integer(8963));
		primes.addElement(new Integer(8969));
		primes.addElement(new Integer(8971));
		primes.addElement(new Integer(8999));
		primes.addElement(new Integer(9001));
		primes.addElement(new Integer(9007));
		primes.addElement(new Integer(9011));
		primes.addElement(new Integer(9013));
		primes.addElement(new Integer(9029));
		primes.addElement(new Integer(9041));
		primes.addElement(new Integer(9043));
		primes.addElement(new Integer(9049));
		primes.addElement(new Integer(9059));
		primes.addElement(new Integer(9067));
		primes.addElement(new Integer(9091));
		primes.addElement(new Integer(9103));
		primes.addElement(new Integer(9109));
		primes.addElement(new Integer(9127));
		primes.addElement(new Integer(9133));
		primes.addElement(new Integer(9137));
		primes.addElement(new Integer(9151));
		primes.addElement(new Integer(9157));
		primes.addElement(new Integer(9161));
		primes.addElement(new Integer(9173));
		primes.addElement(new Integer(9181));
		primes.addElement(new Integer(9187));
		primes.addElement(new Integer(9199));
		primes.addElement(new Integer(9203));
		primes.addElement(new Integer(9209));
		primes.addElement(new Integer(9221));
		primes.addElement(new Integer(9227));
		primes.addElement(new Integer(9239));
		primes.addElement(new Integer(9241));
		primes.addElement(new Integer(9257));
		primes.addElement(new Integer(9277));
		primes.addElement(new Integer(9281));
		primes.addElement(new Integer(9283));
		primes.addElement(new Integer(9293));
		primes.addElement(new Integer(9311));
		primes.addElement(new Integer(9319));
		primes.addElement(new Integer(9323));
		primes.addElement(new Integer(9337));
		primes.addElement(new Integer(9341));
		primes.addElement(new Integer(9343));
		primes.addElement(new Integer(9349));
		primes.addElement(new Integer(9371));
		primes.addElement(new Integer(9377));
		primes.addElement(new Integer(9391));
		primes.addElement(new Integer(9397));
		primes.addElement(new Integer(9403));
		primes.addElement(new Integer(9413));
		primes.addElement(new Integer(9419));
		primes.addElement(new Integer(9421));
		primes.addElement(new Integer(9431));
		primes.addElement(new Integer(9433));
		primes.addElement(new Integer(9437));
		primes.addElement(new Integer(9439));
		primes.addElement(new Integer(9461));
		primes.addElement(new Integer(9463));
		primes.addElement(new Integer(9467));
		primes.addElement(new Integer(9473));
		primes.addElement(new Integer(9479));
		primes.addElement(new Integer(9491));
		primes.addElement(new Integer(9497));
		primes.addElement(new Integer(9511));
		primes.addElement(new Integer(9521));
		primes.addElement(new Integer(9533));
		primes.addElement(new Integer(9539));
		primes.addElement(new Integer(9547));
		primes.addElement(new Integer(9551));
		primes.addElement(new Integer(9587));
		primes.addElement(new Integer(9601));
		primes.addElement(new Integer(9613));
		primes.addElement(new Integer(9619));
		primes.addElement(new Integer(9623));
		primes.addElement(new Integer(9629));
		primes.addElement(new Integer(9631));
		primes.addElement(new Integer(9643));
		primes.addElement(new Integer(9649));
		primes.addElement(new Integer(9661));
		primes.addElement(new Integer(9677));
		primes.addElement(new Integer(9679));
		primes.addElement(new Integer(9689));
		primes.addElement(new Integer(9697));
		primes.addElement(new Integer(9719));
		primes.addElement(new Integer(9721));
		primes.addElement(new Integer(9733));
		primes.addElement(new Integer(9739));
		primes.addElement(new Integer(9743));
		primes.addElement(new Integer(9749));
		primes.addElement(new Integer(9767));
		primes.addElement(new Integer(9769));
		primes.addElement(new Integer(9781));
		primes.addElement(new Integer(9787));
		primes.addElement(new Integer(9791));
		primes.addElement(new Integer(9803));
		primes.addElement(new Integer(9811));
		primes.addElement(new Integer(9817));
		primes.addElement(new Integer(9829));
		primes.addElement(new Integer(9833));
		primes.addElement(new Integer(9839));
		primes.addElement(new Integer(9851));
		primes.addElement(new Integer(9857));
		primes.addElement(new Integer(9859));
		primes.addElement(new Integer(9871));
		primes.addElement(new Integer(9883));
		primes.addElement(new Integer(9887));
		primes.addElement(new Integer(9901));
		primes.addElement(new Integer(9907));
		primes.addElement(new Integer(9923));
		primes.addElement(new Integer(9929));
		primes.addElement(new Integer(9931));
		primes.addElement(new Integer(9941));
		primes.addElement(new Integer(9949));
		primes.addElement(new Integer(9967));
		primes.addElement(new Integer(9973));
		primeArray = new int[primes.size()];
		for (int i = 0; i < primes.size(); i++)
		{
			primeArray[i] = ((Integer) primes.elementAt(i)).intValue();
		}	
	}
	public String getFactorString(int numberIn)
	{
		Vector f = this.getFactors(numberIn);
		StringBuffer s = new StringBuffer("Here are the prime factors for " + numberIn + ":\n\n");
		if (f.size() == 1)
		{
			s.append(numberIn + " is prime!");
		}		
		else
		{	
			for (int i = 0; i < f.size(); i++)
			{
				s.append(((Integer) f.elementAt(i)).toString() + "\n");
			}	
		}	
		return s.toString();
	}	
	private Vector getFactors(int numberIn)
	{
		int i = 0, n = numberIn;
		Vector factors = new Vector();
		while (i < primeArray.length && primeArray[i] <= n && n > 1)
		{
			int factor = primeArray[i];
			if ((double) n/factor == (int)(n/factor))
			{
				factors.addElement(new Integer(factor));
				log("Factor " + factor);
				n /= factor;
			}
			else
			{
				i++;
			}
		}
		log("Number of factors is " + factors.size());
		return factors;
	}
	public static void main (String[] args)
	{
		Puzzle.loadPrimes();
		Puzzle p = new Puzzle(24576);
		p.log("done");
	}	
}
